# Copyright 2026 50Hertz Transmission GmbH and Elia Transmission Belgium
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file,
# you can obtain one at https://mozilla.org/MPL/2.0/.
# Mozilla Public License, version 2.0

name: ga_config
random_seed: 34523412
runtime_seconds: 60
switching_distance: 20
n_worst_contingencies: 2
substation_split_prob: 0.1
