# is there a way to only include certain folder?
extend-exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    ".decontainer",
    ".github",
    ".mypy_cache",
    ".ruff_cache",
    "artifacts",
    "data",
    "docs",
    "*.ipynb",
    "*.uct"
]

# Setting for formatter -> breaks lines at 125
line-length = 125
indent-width = 4

# turn on obvious fixes
# e.g. Returns: -> Returns
# maybe not hardcoded here but used when called?
# fix = true

[lint]
exclude = ["tests/**/*"]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
# https://docs.astral.sh/ruff/rules/
select = [
    "ANN", # flake8-annotations
    "ARG", # finds unused arguments
    "B", # flake8-bugbear, mainly for: mutable-argument-default (B006)
    "C901", # Checks for functions with a high McCabe complexity.
    "F", # Pyflakes
    "E", # pycodestyle   code
    "W", # pycodestyle warnings
    "I", # Isort
    "N", # pep8-naming
    "D", # pydocstyle    doc
    "D100",
    "D417", # Missing argument description in the docstring for {definition}: {name}
    "D418", # Function decorated with @overload shouldn't contain a docstring
    "YTT", # flake8-2020 TODO -> select all flake8 settings
    "S", # flake8-bandit
    "PL", # Pylint -> check if submodules active: Convention (C), Error (E), Refactor (R), Warning (W) -> PLC for convention
    "FLY", # flynt static-join-to-f-string
    # "DOC", # pydoclint only in preview mode -> not stable
    "RUF", # Ruff-specific rules
    "RET", # flake8-return
    "T20" # print() found
    ]
ignore = [
    "S101", # S101 Use of `assert` detected
    "S301", # S301 Pickle is used
    "F722", # jax typing: e.g. Shaped[Array, " dim1"] -> F722 Syntax error in forward annotation: ` dim1`
    "D400", # Checks for docstrings in which the first line does not end in a period.
    "PLR2004", # eg. if value == 2 -> PLR2004 Magic value used in comparison
    "N805", # First argument of a method should be named `self` -> cls (pydantic)
    "RET504", # Unnecessary assignment to `variable` before `return` statement
    "RUF005", # Consider `(*data, k)` instead of concatenation
    "PLW1641", # Object does not implement `__hash__` method TODO: fix me
]

typing-modules = ["typing", "beartype.typing"]

# Allow fix for all enabled rules (when `--fix` / fix = true) is provided.
# fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"


# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

# 4. Ignore `E402` (import violations) in all `__init__.py` files, and in selected subdirectories.
[lint.per-file-ignores]
"__init__.py" = ["E402", "D104"]
"**/{tests,docs,tools}/*" = ["E402", "D"]
"example_grids.py" = ["D"] # TODO -> doc for all grids
"powsybl_backend.py" = ["B019"] # B019 Use of `functools.lru_cache` or `functools.cache` on methods can lead to memory leaks

[lint.pydocstyle]
convention = "numpy"

[lint.pylint]
max-args = 10
max-statements = 50
