# Copyright 2026 50Hertz Transmission GmbH and Elia Transmission Belgium
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file,
# you can obtain one at https://mozilla.org/MPL/2.0/.
# Mozilla Public License, version 2.0

# Assessment config for benchmark.assess_benchmarks
# Default paths; override on CLI: root=..., save=..., print=false
root: ${oc.env:PWD}/data
save: null  # e.g. /workspaces/ToOp/data/aggregate_report.json
print: true

hydra:
  run:
    dir: ${root}/hydra_assess/${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ${root}/hydra_assess/sweeps
    subdir: ${hydra.job.num}
  job:
    chdir: True
