# Copyright 2026 50Hertz Transmission GmbH and Elia Transmission Belgium
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file,
# you can obtain one at https://mozilla.org/MPL/2.0/.
# Mozilla Public License, version 2.0

# Grid config (Hydra group: grid=config_grid_node_breaker)
name: config_grid_node_breaker
output_dir: ${oc.env:PWD}/data/grid_node_breaker/results/
grid_file: ${oc.env:PWD}/data/grid_node_breaker/grid.xiidm
grid_type: powsybl
