# configs for ToOp benchmark
output_dir: /workspaces/data/grid_node_breaker/results/
grid_file: /workspaces/data/grid_node_breaker/grid.xiidm
cutoff_voltage: 10

hydra: 
  run:
    dir: ${output_dir}/hydra/
