# Grid config (Hydra group: grid=config_grid_node_breaker)
name: config_grid_node_breaker
output_dir: /workspaces/data/grid_node_breaker/results/
grid_file: /workspaces/data/grid_node_breaker/grid.xiidm
grid_type: powsybl
