name: Fossa scan

on: push

jobs:
  license-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: License Header Check
        uses: B1NARY-GR0UP/nwa@main
        with:
          version: latest        # (optional) version of nwa to use; default: latest
          cmd: check             # (optional) command to execute; options: `check`, `add`, `update`, `remove`; default: check
          path: .nwa-config.yaml # (optional) configuration file path; default: .nwa-config.yaml
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: fossa-analyze
        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          run-tests: false # Add another run with run-tests: true if ci should fail on issues
      - id: fossa-test
        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          run-tests: true # Add another run with run-tests: true if ci should fail on issues
