# Copyright 2025 50Hertz Transmission GmbH and Elia Transmission Belgium
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file,
# you can obtain one at https://mozilla.org/MPL/2.0/.
# Mozilla Public License, version 2.0

name: test notebooks

on: push

permissions: {}

jobs:
  test-example-notebooks:
    permissions:
      contents: read
    runs-on:
      labels: Runner-ToOp-Projects
    timeout-minutes: 10
    env:
      UV_PROJECT: ./
    steps:
    - name: Check out repository code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

    - name: Install uv
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867

    - name: "Set up Python"
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
      with:
        python-version-file: "pyproject.toml"

    - name: Install dependencies
      run: uv sync --all-groups --all-extras --frozen

    - name: set PY
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

    - name: Verify jupyter installation
      run: uv run jupyter --version

    - name: Test example notebooks
      run: uv run pytest -n auto --dist loadgroup notebooks/tests
