name: validate_commits

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate_commits:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --frozen --only-group ci

      - name: Validate commit messages
        run: |

          badCommits=()

          newCommits=$(git log origin/$GITHUB_BASE_REF..origin/$GITHUB_HEAD_REF --pretty=format:'%H')

          for commit in $newCommits; do
              echo "Validating commit: $commit"
              msg=$(git show --no-patch --format=%B $commit)
              echo "Message: $msg"

              if ! uv run --no-sync cz check --message "$msg" >/dev/null 2>&1; then
                badCommits+=($commit)
              fi

          done

          if (( ${#badCommits[@]} > 0 )); then
              echo "Invalid commit messages found:"
              for commit in "${badCommits[@]}"; do
                  echo "  $commit -> $(git show -s --format=%s "$commit")"
              done
              exit 1
          fi
