# Copyright 2026 50Hertz Transmission GmbH and Elia Transmission Belgium SA/NV
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file,
# you can obtain one at https://mozilla.org/MPL/2.0/.
# Mozilla Public License, version 2.0

name: validate_commits

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  validate_commits:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867

      - name: "Set up Python"
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --frozen --only-group ci

      - name: Validate commit messages
        run: |

          badCommits=()

          newCommits=$(git log origin/$GITHUB_BASE_REF..origin/$GITHUB_HEAD_REF --pretty=format:'%H')

          for commit in $newCommits; do
              echo "Validating commit: $commit"
              msg=$(git show --no-patch --format=%B $commit)
              echo "Message: $msg"

              if ! uv run --no-sync cz check --message "$msg" >/dev/null 2>&1; then
                badCommits+=($commit)
              fi

          done

          if (( ${#badCommits[@]} > 0 )); then
              echo "Invalid commit messages found:"
              for commit in "${badCommits[@]}"; do
                  echo "  $commit -> $(git show -s --format=%s "$commit")"
              done
              exit 1
          fi
